# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update data

on:
  schedule:
    - cron:  '*/10 * * * *' # every ten minutes when it isn't night time
#  push:
#    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update data
      uses: actions/setup-node@v1
      with:
        node-version: 15
    - run: npm ci
    - run: node index.js
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'main'
